/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./script.min.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffb2b9",
        "primary-container": "#bc87fe",
        "on-secondary-fixed": "#00463f",
        "secondary": "#4af8e3",
        "on-primary-fixed": "#000000",
        "tertiary": "#ff9dac",
        "error-container": "#a70138",
        "on-primary": "#440080",
        "secondary-container": "#006a60",
        "outline": "#767575",
        "outline-variant": "#484847",
        "on-tertiary-container": "#5b0a22",
        "surface-container-low": "#131313",
        "tertiary-fixed": "#ff8fa2",
        "primary-fixed-dim": "#af7aef",
        "surface-container": "#1a1a1a",
        "surface-dim": "#0e0e0e",
        "error": "#ff6e84",
        "inverse-surface": "#fcf9f8",
        "on-surface-variant": "#adaaaa",
        "on-error": "#490013",
        "primary": "#c799ff",
        "on-background": "#ffffff",
        "surface-variant": "#262626",
        "primary-fixed": "#bc87fe",
        "on-secondary-fixed-variant": "#00655b",
        "inverse-primary": "#7744b5",
        "tertiary-container": "#fb899c",
        "secondary-dim": "#33e9d5",
        "surface": "#0e0e0e",
        "primary-dim": "#ba85fb",
        "on-primary-container": "#340064",
        "surface-bright": "#2c2c2c",
        "secondary-fixed-dim": "#33e9d5",
        "inverse-on-surface": "#565555",
        "background": "#0e0e0e",
        "tertiary-fixed-dim": "#f18194",
        "on-surface": "#ffffff",
        "on-secondary-container": "#dcfff8",
        "surface-container-lowest": "#000000",
        "surface-tint": "#c799ff",
        "error-dim": "#d73357",
        "on-primary-fixed-variant": "#40007a",
        "secondary-fixed": "#4af8e3",
        "on-secondary": "#005b51",
        "on-tertiary-fixed": "#390010",
        "tertiary-dim": "#eb7c8f",
        "surface-container-high": "#20201f",
        "surface-container-highest": "#262626",
        "on-tertiary-fixed-variant": "#6c192e",
        "on-tertiary": "#69162c"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
